import { useState, useCallback } from 'react';
// FIX: Import missing types.
import type { TrainingActivity, TrainingModule, Trainee, Tool, QuizQuestion } from '../types';
import { Icons } from '../components/Icons';

const INITIAL_ACTIVITIES: TrainingActivity[] = [
    {
        id: 'act1',
        title: 'Angry Customer Scenario',
        category: 'Practice',
        objective: 'Train pharmacists to handle customer complaints effectively and de-escalate anger.',
        duration: 20,
        tools: 'Printed scenario cards for each participant.',
        instructions: '1. Divide trainees into pairs.\n2. Each pair takes on the role of "pharmacist" and "angry customer".\n3. The "customer" acts out a specific complaint scenario (e.g., missing medication, wrong price).\n4. The "pharmacist" must apply active listening, calming techniques, and problem-solving skills.\n5. After 7 minutes, switch roles.\n6. Finally, hold a group discussion to share experiences.',
        pharmaExample: 'A customer complains that the medication they received has side effects they were not told about.',
        groupSize: 'Small Groups',
        tags: ['role-play', 'communication', 'problem-solving'],
    },
    {
        id: 'act2',
        title: 'Two Truths and a Lie',
        category: 'Openers',
        objective: 'Build rapport and get to know each other',
        duration: 9,
        instructions: '1. Ask each participant to write down two true statements about themselves and one lie.\n2. One by one, each person shares their three statements with the group.\n3. The rest of the group votes on which statement they think is the lie.\n4. After everyone has guessed, the person reveals the lie.',
        tools: 'Zoom, Mentimeter, Slido',
        pharmaExample: '"I worked on a clinical trial; I audited 20 pharmacies; I have never used Excel."',
        groupSize: 'Small Groups',
        tags: ['icebreaker', 'team-building', 'virtual-friendly'],
    },
    {
        id: 'act3',
        title: 'Case Study: Drug Interactions',
        category: 'Practice',
        objective: 'Enhance pharmacists\' ability to identify and review potential drug interactions on a prescription.',
        duration: 25,
        tools: 'Printed prescriptions with intentional drug interactions.',
        instructions: '1. Distribute case studies (prescriptions) to small groups (3-4 people).\n2. Ask each group to review the prescription and identify any potential drug interactions.\n3. The group should discuss the severity of the interaction and propose solutions (e.g., contact the doctor, advise the patient).\n4. Each group presents its findings to the rest of the trainees.',
        pharmaExample: 'Reviewing a prescription for an elderly patient taking multiple medications for chronic diseases and identifying critical interactions.',
        groupSize: 'Small Groups',
        tags: ['analytical-skills', 'case-study', 'collaboration'],
    },
    {
        id: 'act4',
        title: 'Virtual Background Stories',
        category: 'Openers',
        objective: 'Creative introductions',
        duration: 10,
        instructions: '1. Ask participants to set a Zoom background that reflects their mood, personality, or the training topic.\n2. Divide them into breakout rooms of 3-4 people.\n3. In the breakout rooms, each person shares the story behind their background.\n4. Bring everyone back to the main room and ask for a few volunteers to share with the whole group.',
        tools: 'Zoom',
        pharmaExample: 'A participant uses a lab background and explains they work in drug formulation.',
        groupSize: 'Both',
        tags: ['icebreaker', 'virtual-friendly', 'creativity'],
    },
    {
        id: 'act5',
        title: 'Introductory Chat Storm',
        category: 'Openers',
        objective: 'Instant engagement',
        duration: 5,
        instructions: '1. Pose a question in the chat (e.g., "In one word, how do you feel about today\'s topic?").\n2. Instruct everyone to type their answer but NOT press Enter yet.\n3. On your signal (e.g., "3, 2, 1, GO!"), everyone hits Enter at the same time.\n4. Read through the "storm" of answers and discuss any interesting themes.',
        tools: 'Zoom',
        pharmaExample: 'Q: "In one word, how do you feel about regulatory inspections?" A: Nervous, Confident.',
        groupSize: 'Big Groups',
        tags: ['quick', 'virtual-friendly', 'engagement', 'no-equipment'],
    },
    {
        id: 'act6',
        title: 'Quick Icebreaker Poll',
        category: 'Openers',
        objective: 'Fun, insightful data',
        duration: 7,
        instructions: '1. Prepare 2-3 poll questions using a tool like Kahoot or Slido.\n2. Mix fun, personal questions (e.g., "Coffee or Tea?") with topic-related ones.\n3. Launch the polls one by one and give participants time to vote.\n4. Share and discuss the results, highlighting any surprising patterns and linking them to the session objectives.',
        tools: 'Kahoot, Slido, Mentimeter',
        pharmaExample: 'Poll: "What\'s most challenging? R&D / Compliance / Patient Safety / Competition."',
        groupSize: 'Both',
    },
    {
        id: 'act7',
        title: 'Name + Emoji Game',
        category: 'Openers',
        objective: 'Light-hearted intros',
        duration: 6,
        instructions: '1. Ask participants to find the "rename" option in the video conferencing tool.\n2. Instruct them to add an emoji after their name that represents their current mood or role.\n3. Go around the "room" and have each person introduce themselves and explain their choice of emoji.',
        tools: 'Zoom',
        pharmaExample: '"Sarah 💊 (Retail Pharmacist)"; "Ahmed 🧪 (QC)."',
        groupSize: 'Small Groups',
    },
    {
        id: 'act8',
        title: 'Show and Tell Object',
        category: 'Openers',
        objective: 'Personal connection',
        duration: 10,
        instructions: '1. Before the session, ask participants to have an object nearby that represents their work or connection to the topic.\n2. During the activity, each person takes a turn holding up their object to the camera.\n3. They have one minute to explain what the object is and why they chose it.',
        tools: 'Zoom, Padlet',
        pharmaExample: 'Someone shows a medicine bottle to represent patient safety.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act9',
        title: 'Topic Word Cloud',
        category: 'Openers',
        objective: 'Visualize expectations',
        duration: 5,
        instructions: '1. Use a tool like Mentimeter to set up a word cloud slide.\n2. Ask the question: "What one word comes to mind when you hear [Your Topic]?".\n3. Share the link or code with participants and have them submit their word.\n4. Display the live, growing word cloud on screen and discuss the most common words.',
        tools: 'Mentimeter',
        pharmaExample: 'Words: Research, Patients, Compliance, Innovation, Safety.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act10',
        title: 'Mini-Debate Starter',
        category: 'Openers',
        objective: 'Spark curiosity',
        duration: 8,
        instructions: '1. Introduce a controversial or thought-provoking statement related to the topic.\n2. Divide participants into breakout groups for 3 minutes to discuss their initial thoughts.\n3. Bring everyone back and have a representative from each group share their main discussion points.\n4. Facilitate a brief, whole-group discussion.',
        tools: 'Zoom, Google Docs',
        pharmaExample: 'Statement: "Generic drugs are just as important as branded ones."',
        groupSize: 'Both',
    },
    {
        id: 'act11',
        title: 'Personal Goal Setting',
        category: 'Openers',
        objective: 'Clarify learning goals',
        duration: 7,
        instructions: '1. Ask participants to think about what they personally want to achieve from the session.\n2. Have them submit one key goal using a tool like Google Forms or Mentimeter.\n3. Share an anonymized summary of the goals with the group.\n4. At the end of the session, revisit these goals to check for achievement.',
        tools: 'Google Forms, Mentimeter',
        pharmaExample: '"I want to improve my knowledge of GMP compliance."',
        groupSize: 'Both',
    },
    {
        id: 'act12',
        title: 'Concept Mapping',
        category: 'Linking & Summarizing',
        objective: 'Connect concepts visually',
        duration: 15,
        instructions: '1. Ask participants to list 4-5 key concepts from the session.\n2. Provide a shared mind-map board (like Miro) and have them add their concepts as nodes.\n3. Instruct them to draw connections between related concepts with lines or arrows.\n4. As a group, review the map, highlighting common links and discussing any misconceptions.',
        tools: 'Miro, MindMeister',
        pharmaExample: 'Map: Drug Discovery -> Clinical Trials -> FDA Approval -> Market.',
        groupSize: 'Both',
        tags: ['visual-thinking', 'collaboration', 'review'],
    },
    {
        id: 'act13',
        title: 'Think-Pair-Share',
        category: 'Linking & Summarizing',
        objective: 'Deepen understanding',
        duration: 10,
        instructions: '1. (Think) Pose a reflection question and give everyone 2 minutes for individual, quiet reflection.\n2. (Pair) Send participants to breakout pairs for 3 minutes to share their ideas with each other.\n3. (Share) Bring everyone back to the main room and ask volunteers to summarize their pair\'s discussion.',
        tools: 'Zoom',
        pharmaExample: 'Q: How does supply chain disruption affect patient access?',
        groupSize: 'Small Groups',
    },
    {
        id: 'act14',
        title: 'Summary Carousel',
        category: 'Linking & Summarizing',
        objective: 'Peer co-creation of summaries',
        duration: 15,
        instructions: '1. Create a shared document (e.g., Google Docs) with a section for each topic covered.\n2. Assign each breakout group to one section to summarize the key points for that topic.\n3. After 3-4 minutes, instruct the groups to "rotate" to the next section in the document.\n4. Groups now add to or edit the summary written by the previous group.\n5. Continue until all groups have contributed to all sections. Debrief the final document.',
        tools: 'Google Docs, Miro',
        pharmaExample: 'Each group summarizes a section of GMP guidelines.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act15',
        title: 'Timeline Builder',
        category: 'Linking & Summarizing',
        objective: 'Show progression of events',
        duration: 10,
        instructions: '1. Give participants a list of key events or concepts from the session.\n2. Using a digital whiteboard like Miro, ask teams to place these items on a timeline in the correct sequence.\n3. Have each group briefly explain their rationale for the order they chose.\n4. Review the final, correct sequence with the whole group.',
        tools: 'Miro, Trello',
        pharmaExample: 'Sequence: Preclinical -> Phase I -> Phase II -> Phase III -> Approval.',
        groupSize: 'Both',
    },
    {
        id: 'act16',
        title: 'Recap Quiz',
        category: 'Linking & Summarizing',
        objective: 'Check knowledge, reinforce',
        duration: 10,
        instructions: '1. Prepare 5 short quiz questions covering the main topics.\n2. Use a tool like Kahoot or Quizizz to run the quiz live.\n3. Display the leaderboard for a fun, competitive element.\n4. Briefly review the answers and clarify any common misconceptions.',
        tools: 'Kahoot, Quizizz',
        pharmaExample: 'Q: Which trial phase involves healthy volunteers?',
        groupSize: 'Both',
        tags: ['quiz', 'assessment', 'engagement', 'virtual-friendly'],
    },
    {
        id: 'act17',
        title: 'Digital Posters',
        category: 'Linking & Summarizing',
        objective: 'Visual summaries',
        duration: 12,
        instructions: '1. Divide participants into small groups.\n2. Ask each group to create a simple digital poster summarizing their key learnings using a tool like Jamboard or Padlet.\n3. Have each group briefly present their poster to the plenary.\n4. Highlight connections between the different posters.',
        tools: 'Jamboard, Padlet',
        pharmaExample: 'Poster: Pharmacovigilance Best Practices.',
        groupSize: 'Both',
    },
    {
        id: 'act18',
        title: 'Pairwise Explanation',
        category: 'Linking & Summarizing',
        objective: 'Reinforce by teaching',
        duration: 10,
        instructions: '1. Pair participants in breakout rooms.\n2. Assign each person one concept from the session.\n3. Each person takes 3 minutes to explain their assigned concept to their partner in their own words.\n4. After both have explained, bring everyone back to debrief on the experience.',
        tools: 'Zoom',
        pharmaExample: 'One explains bioequivalence, the other stability testing.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act19',
        title: 'Linking Statements',
        category: 'Linking & Summarizing',
        objective: 'Show concept relationships',
        duration: 10,
        instructions: '1. Prepare a set of related statements or concepts on digital sticky notes (e.g., in Miro).\n2. Ask participants to drag and connect the notes that are related to each other.\n3. As a facilitator, review the connections made by the group and explain the correct or most important links.',
        tools: 'Padlet, Miro',
        pharmaExample: 'Connect Drug Recalls -> Patient Safety -> Adverse Event Reporting.',
        groupSize: 'Both',
    },
    {
        id: 'act20',
        title: 'Group Chat Summary',
        category: 'Linking & Summarizing',
        objective: 'Capture discussion in chat',
        duration: 8,
        instructions: '1. Assign one participant in each breakout group to be the "scribe".\n2. As the group discusses, the scribe types the key points and conclusions into the breakout room chat.\n3. When returning to the main room, the scribe can copy-paste their summary into the main chat for everyone to see.',
        tools: 'Zoom, Microsoft Teams',
        pharmaExample: 'Scribe notes discussion on ethical pharma marketing.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act21',
        title: 'Analogy Builder',
        category: 'Linking & Summarizing',
        objective: 'Deepen understanding',
        duration: 10,
        instructions: '1. Pose the question: "If [this concept] were a [car/animal/food], what would it be and why?".\n2. Give participants a few minutes to think and write their analogy in the chat or on a Padlet board.\n3. Read some of the most insightful or creative analogies aloud and discuss them.',
        tools: 'Zoom, Padlet',
        pharmaExample: '"GMP is like a seatbelt – it prevents accidents."',
        groupSize: 'Both',
    },
    {
        id: 'act22',
        title: 'Interactive Lecture with Polls',
        category: 'Delivery',
        objective: 'Keep lecture engaging',
        duration: 25,
        instructions: '1. Prepare your lecture content as usual.\n2. Identify key points every 8-10 minutes where you can check for understanding or ask for an opinion.\n3. Insert a poll (using Mentimeter or Zoom polls) at these key points.\n4. Discuss the poll results before moving on with the lecture.',
        tools: 'Mentimeter, Zoom',
        pharmaExample: 'Poll: What impacts drug pricing most?',
        groupSize: 'Big Groups',
    },
    {
        id: 'act23',
        title: 'Live Demonstration',
        category: 'Delivery',
        objective: 'Show practical use',
        duration: 18,
        instructions: '1. Prepare the software or process you want to demonstrate.\n2. Share your screen with the audience.\n3. Walk through the process step-by-step, explaining what you are doing and why.\n4. Pause periodically to ask for questions from the audience.',
        tools: 'Zoom, Microsoft Teams',
        pharmaExample: 'Demo of pharmacovigilance database entry.',
        groupSize: 'Both',
    },
    {
        id: 'act24',
        title: 'Case Study Breakouts',
        category: 'Delivery',
        objective: 'Analytical thinking',
        duration: 23,
        instructions: '1. Share a case study document (e.g., PDF or Google Doc) with participants.\n2. Divide them into breakout groups to analyze the case and answer specific questions.\n3. Have each group submit their solutions in a shared document.\n4. Debrief the case together in the main room, calling on different groups to share their findings.',
        tools: 'Google Docs, Zoom',
        pharmaExample: 'Case: A contaminated vaccine batch recall.',
        groupSize: 'Both',
    },
    {
        id: 'act25',
        title: 'Guided Discussion',
        category: 'Delivery',
        objective: 'Group sense-making',
        duration: 18,
        instructions: '1. Prepare 2-3 key questions to guide the discussion.\n2. Pose the first question and invite participants to share their thoughts.\n3. Use a digital tool like Padlet to capture all answers and ideas visually.\n4. At the end, summarize the key themes that emerged from the discussion.',
        tools: 'Padlet',
        pharmaExample: '“What’s the biggest pharma supply chain challenge?”',
        groupSize: 'Both',
    },
    {
        id: 'act26',
        title: 'Role-Play Demo',
        category: 'Delivery',
        objective: 'Experiential learning',
        duration: 18,
        instructions: '1. Choose 2-3 volunteers to act out a specific scenario in front of the group.\n2. Assign roles and provide a brief context.\n3. Instruct the rest of the group to act as observers and take notes on what they see.\n4. After the role-play, facilitate a debrief discussion with the entire group.',
        tools: 'Zoom',
        pharmaExample: 'Rep explains new oncology drug to doctor.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act27',
        title: 'Collaborative Docs',
        category: 'Delivery',
        objective: 'Build knowledge',
        duration: 23,
        instructions: '1. Provide a shared document (e.g., Google Docs) divided into different sections.\n2. Assign each breakout group to complete one section.\n3. After the breakout session, have each group present their contribution back in the main room.',
        tools: 'Google Docs',
        pharmaExample: 'Drug Development Challenges in Emerging Markets.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act28',
        title: 'Virtual Gallery Walk',
        category: 'Delivery',
        objective: 'Compare outputs',
        duration: 18,
        instructions: '1. Assign groups a task to create a visual output (e.g., a poster on Jamboard).\n2. Once complete, ask everyone to "walk" through the virtual gallery (the Jamboard file) and view the work of other groups.\n3. Encourage participants to leave comments or questions on sticky notes on their peers\' work.',
        tools: 'Jamboard',
        pharmaExample: 'Posters: Types of clinical trial designs.',
        groupSize: 'Both',
    },
    {
        id: 'act29',
        title: 'Fishbowl Discussion',
        category: 'Delivery',
        objective: 'Deep group discussion',
        duration: 23,
        instructions: '1. Assign 4 participants to be in the "fishbowl" (the inner circle) and turn their cameras on.\n2. The rest of the group (outer circle) turns their cameras off and observes.\n3. The fishbowl group discusses a specific topic for 5-7 minutes.\n4. Rotate new participants into the fishbowl and continue the discussion.',
        tools: 'Zoom',
        pharmaExample: 'Debate: Should pharma focus on rare diseases?',
        groupSize: 'Big Groups',
    },
    {
        id: 'act30',
        title: 'Interactive Polling',
        category: 'Delivery',
        objective: 'Check understanding',
        duration: 10,
        instructions: '1. Prepare a mix of poll questions: knowledge checks, opinion polls, and prediction questions.\n2. Launch these polls at key moments during your presentation.\n3. Always discuss the results and any patterns before continuing with your content.',
        tools: 'Mentimeter, Slido',
        pharmaExample: 'Q: Top cause of drug recalls?',
        groupSize: 'Both',
    },
    {
        id: 'act31',
        title: 'Video Case Analysis',
        category: 'Delivery',
        objective: 'Visual engagement',
        duration: 18,
        instructions: '1. Find a short, relevant video (e.g., from YouTube).\n2. Play the video for the group.\n3. Send participants into breakout groups to discuss specific questions related to the video.\n4. Bring them back to the main room to share their insights.',
        tools: 'YouTube, Zoom',
        pharmaExample: 'Video: COVID-19 vaccine approval journey.',
        groupSize: 'Both',
    },
    {
        id: 'act32',
        title: 'Emoji Check-In',
        category: 'Energizers',
        objective: 'Mood check + energy',
        duration: 3,
        instructions: '1. Ask: "Share your current mood with just one emoji."\n2. Instruct everyone to post their emoji in the chat simultaneously.\n3. Read aloud some of the interesting or funny ones to acknowledge the group\'s energy.\n4. Link it back to the session: "Great to see the energy! Let\'s dive in."',
        tools: 'Zoom',
        pharmaExample: '🤗 (after GMP), 💪 (after compliance talk).',
        groupSize: 'Both',
    },
    {
        id: 'act33',
        title: 'Virtual Dance Break',
        category: 'Energizers',
        objective: 'Boost energy & fun',
        duration: 4,
        instructions: '1. Choose an upbeat, instrumental song.\n2. Share your computer audio through the conferencing tool.\n3. Encourage participants to stand up, stretch, move, or even dance on camera for the duration of the song.\n4. Keep it light-hearted and optional.',
        tools: 'Zoom, YouTube',
        pharmaExample: 'Play instrumental upbeat music.',
        groupSize: 'Big Groups',
        tags: ['fun', 'movement', 'quick', 'virtual-friendly'],
    },
    {
        id: 'act34',
        title: 'Mini Kahoot Quiz',
        category: 'Energizers',
        objective: 'Fun + review',
        duration: 6,
        instructions: '1. Prepare 3-5 quick, light-hearted questions (can be fun facts, session trivia, or general knowledge).\n2. Share the Kahoot code and let participants join from their phones.\n3. Run the fast-paced quiz with the leaderboard displayed to create excitement.',
        tools: 'Kahoot, Quizizz',
        pharmaExample: 'Q: What\'s Phase IV trial called?',
        groupSize: 'Both',
    },
    {
        id: 'act35',
        title: 'Charades (Topic)',
        category: 'Energizers',
        objective: 'Fun application',
        duration: 9,
        instructions: '1. Prepare a list of words or concepts related to the training topic.\n2. Privately message a word to a volunteer.\n3. The volunteer acts out the word silently on camera.\n4. Other participants type their guesses in the chat. The first correct guess goes next.',
        tools: 'Zoom',
        pharmaExample: 'Act out tablet compression -> team guesses.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act36',
        title: 'Quick Draw Challenge',
        category: 'Energizers',
        objective: 'Spark creativity',
        duration: 6,
        instructions: '1. Give participants a prompt (e.g., "Draw how you feel about today\'s topic").\n2. Allow 1-2 minutes for them to draw on a piece of paper or a digital tool like Jamboard.\n3. Have everyone share by holding their drawing up to the camera or uploading it digitally.',
        tools: 'Jamboard',
        pharmaExample: 'Prompt: "Draw pharma innovation."',
        groupSize: 'Both',
    },
    {
        id: 'act37',
        title: 'Scavenger Hunt',
        category: 'Energizers',
        objective: 'Movement & fun',
        duration: 8,
        instructions: '1. Give the group a prompt, like "Find something red" or "Bring an object you use daily for your work."\n2. Give everyone 1-2 minutes to find the object and return.\n3. Have a few participants share their object on camera and briefly explain what it is.',
        tools: 'Zoom',
        pharmaExample: 'Show something that represents patient safety.',
        groupSize: 'Both',
    },
    {
        id: 'act38',
        title: 'Emoji Story Chain',
        category: 'Energizers',
        objective: 'Build creativity',
        duration: 6,
        instructions: '1. Start a story in the chat using only 3-4 emojis (e.g., "👨‍⚕️💊➡️😊").\n2. Instruct each participant to add one emoji to continue the story.\n3. After several people have contributed, read the final emoji chain aloud as a "story."',
        tools: 'Zoom',
        pharmaExample: 'Story: 💊➡️😋➡️🚚➡️🏥➡️👨‍⚕️ (medicine to patient).',
        groupSize: 'Big Groups',
    },
    {
        id: 'act39',
        title: 'Breakout Labs',
        category: 'Practice',
        objective: 'Apply learning',
        duration: 23,
        instructions: '1. Provide a specific challenge or problem to solve.\n2. Send participants into breakout groups to work on the challenge, using a shared document to record their ideas.\n3. Bring everyone back and have each group present a 2-minute summary of their solution.',
        tools: 'Google Docs, Zoom',
        pharmaExample: 'Solve: High dropout in clinical trial – suggest solutions.',
        groupSize: 'Both',
    },
    {
        id: 'act40',
        title: 'Role-Play Scenarios',
        category: 'Practice',
        objective: 'Practice skills',
        duration: 18,
        instructions: '1. Provide groups with specific scenarios and assign roles (e.g., Doctor, Sales Rep).\n2. Send them to breakout groups to act out the role-play.\n3. After a set time, bring them back to the main room to debrief the experience and share key learnings.',
        tools: 'Google Docs, Zoom',
        pharmaExample: 'Regulatory agency vs pharma company approval meeting.',
        groupSize: 'Small Groups',
        tags: ['role-play', 'communication', 'skill-practice'],
    },
    {
        id: 'act41',
        title: 'Simulation Game',
        category: 'Practice',
        objective: 'Practice decision-making',
        duration: 35,
        instructions: '1. Use a dedicated online simulation platform.\n2. Divide participants into teams and explain the rules and objectives of the simulation.\n3. Allow teams to make their choices within the simulation.\n4. Conclude with a thorough debrief, discussing the consequences of their decisions.',
        tools: 'Forio, SimulTrain',
        pharmaExample: 'Allocate R&D budget for new drug pipeline.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act42',
        title: 'Peer Coaching Triads',
        category: 'Practice',
        objective: 'Peer learning',
        duration: 20,
        instructions: '1. Divide participants into groups of 3.\n2. Assign roles: "Practitioner" (presents a challenge), "Coach" (asks questions), and "Observer" (takes notes).\n3. Rotate the roles every 5-6 minutes so everyone gets a chance to be the coach.\n4. Provide a feedback template for the observer to use.',
        tools: 'Zoom',
        pharmaExample: 'Challenge: Improving compliance in sales reps.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act43',
        title: 'Digital Escape Room',
        category: 'Practice',
        objective: 'Problem-solving + fun',
        duration: 28,
        instructions: '1. Create a series of online puzzles linked to the training content using tools like Genially or Google Forms.\n2. Divide participants into teams.\n3. The first team to solve all the puzzles and "escape" wins the challenge.',
        tools: 'Genially, Google Forms',
        pharmaExample: 'Puzzles: Regulatory acronyms, GMP standards.',
        groupSize: 'Both',
    },
    {
        id: 'act44',
        title: 'Challenge Projects',
        category: 'Practice',
        objective: 'Apply knowledge',
        duration: 35,
        instructions: '1. Assign a real-world workplace challenge to small groups.\n2. Give them time to brainstorm, research, and develop a proposed solution.\n3. Have each group present their solution to the rest of the participants for feedback.',
        tools: 'Miro, Google Docs',
        pharmaExample: 'Plan to reduce counterfeit drugs in Africa.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act45',
        title: 'Mistake Recovery',
        category: 'Practice',
        objective: 'Learn from failure',
        duration: 23,
// FIX: Add missing 'tools' property.
        tools: 'Zoom, Google Docs',
        instructions: '1. Provide a scenario where a mistake or failure has occurred.\n2. In breakout groups, have teams analyze what went wrong and develop a recovery plan.\n3. Bring everyone back to share and discuss the different recovery strategies.',
        pharmaExample: 'Product launch failed due to poor forecasting.',
        groupSize: 'Both',
    },
    {
        id: 'act46',
        title: 'Peer Teaching',
        category: 'Practice',
        objective: 'Reinforce learning',
        duration: 18,
// FIX: Add missing 'tools' property.
        tools: 'Zoom',
        instructions: '1. Assign each participant a small concept from the training.\n2. Give them a few minutes to prepare to teach it.\n3. Have each person briefly teach their concept to their peers in small breakout groups.\n4. Encourage peers to ask questions to the "teacher".',
        pharmaExample: 'Teach: drug labeling rules, bioequivalence, pharmacovigilance.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act47',
        title: 'Reflection Circle',
        category: 'Closing',
        objective: 'Capture key insights',
        duration: 6,
        instructions: '1. Ask everyone a final reflection question, such as: "What is your single biggest takeaway from today?".\n2. Have each participant type their answer in the chat.\n3. Read through the answers and highlight common themes or surprising insights to close the session.',
        tools: 'Zoom',
        pharmaExample: '"Patient safety must guide every decision."',
        groupSize: 'Both',
    },
    {
        id: 'act48',
        title: 'Commitment Board',
        category: 'Closing',
        objective: 'Accountability',
        duration: 9,
        instructions: '1. Set up a "commitment wall" on a tool like Jamboard or Padlet.\n2. Ask each participant to post one specific action they will take based on the training.\n3. Read a few of the commitments aloud to the group.\n4. Take a screenshot to share with the group later as a reminder.',
        tools: 'Padlet, Jamboard',
        pharmaExample: '"I will update our GMP checklist weekly."',
        groupSize: 'Both',
    },
    {
        id: 'act49',
        title: 'One-Minute Paper',
        category: 'Closing',
        objective: 'Reflection & evaluation',
        duration: 5,
        instructions: '1. Share a link to a simple Google Form with one or two questions (e.g., "What was your key insight?" and "What questions remain?").\n2. Give participants 1-2 minutes to write their short reflections.\n3. Thank them and promise to review their feedback.',
        tools: 'Google Forms',
        pharmaExample: '"Main insight: role of Phase IV monitoring."',
        groupSize: 'Both',
    },
    {
        id: 'act50',
        title: 'Appreciation Round',
        category: 'Closing',
        objective: 'End with positivity',
        duration: 5,
        instructions: '1. Ask participants to think of something they appreciate about a peer or the group discussion.\n2. Go around the virtual room and have each person share their appreciation aloud or in the chat.\n3. This creates a positive and collaborative end to the session.',
        tools: 'Zoom',
        pharmaExample: '"Thanks to Ahmed for sharing QA experience."',
        groupSize: 'Both',
    },
    {
        id: 'act51',
        title: 'Action Planning',
        category: 'Closing',
        objective: 'Translate learning',
        duration: 9,
        instructions: '1. Ask participants to write down 3 concrete steps they will take after the training.\n2. Use a shared tool like Padlet or Google Docs for them to post their action plans.\n3. Highlight a few strong examples to inspire others.',
        tools: 'Google Docs, Padlet',
        pharmaExample: '1. Revise protocols 2. Train team 3. Review compliance data.',
        groupSize: 'Both',
    },
    {
        id: 'act52',
        title: 'Virtual Graduation',
        category: 'Closing',
        objective: 'Celebrate completion',
        duration: 8,
        instructions: '1. Share some upbeat music.\n2. Display a "Congratulations" slide with the names of the participants.\n3. Optionally, share digital certificates via email.\n4. Take a group screenshot with everyone waving or giving a thumbs-up.',
        tools: 'Zoom, Canva',
        pharmaExample: '"Congratulations Pharma Leaders!"',
        groupSize: 'Big Groups',
    },
    {
        id: 'act53',
        title: 'Reflection Videos',
        category: 'Closing',
        objective: 'Personal reflection',
        duration: 11,
        instructions: '1. Ask participants to record a 1-minute reflection video on their key learnings.\n2. Use a tool like Flipgrid or Loom for them to easily record and upload.\n3. Encourage them to watch their peers\' videos to see different perspectives.',
        tools: 'Flipgrid, Loom',
        pharmaExample: '"I learned ethical marketing is key to trust."',
        groupSize: 'Both',
    },
    {
        id: 'act54',
        title: 'Resource Marketplace',
        category: 'Closing',
        objective: 'Share useful links',
        duration: 6,
        instructions: '1. Create a shared Google Doc titled "Resources."\n2. Ask participants to add at least one useful link, tool, or article related to the topic.\n3. Make the document available to everyone after the session as a co-created resource.',
        tools: 'Google Docs',
        pharmaExample: 'WHO GMP guideline, FDA site.',
        groupSize: 'Both',
    },
    {
        id: 'act55',
        title: 'Follow-Up Planning',
        category: 'Closing',
        objective: 'Accountability post-training',
        duration: 10,
        instructions: '1. Pair participants in breakout rooms.\n2. Ask them to share their action plan with their partner.\n3. Have them agree to a brief check-in with each other in one week to discuss their progress.\n4. Collect the partner names in the chat to encourage accountability.',
        tools: 'Zoom',
        pharmaExample: 'Pair agrees to follow up on compliance audit steps.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act56',
        title: 'Word Cloud Takeaway',
        category: 'Closing',
        objective: 'Visual summary',
        duration: 5,
        instructions: '1. Open a Mentimeter word cloud.\n2. Ask: "Enter one word that captures your main learning from today."\n3. Display the live word cloud as a visual summary of the session\'s impact.',
        tools: 'Mentimeter',
        pharmaExample: 'Words: Compliance, Safety, Patients, Innovation.',
        groupSize: 'Big Groups',
    }
];

const INITIAL_TOOLS: Tool[] = [
    {
        id: 'tool1',
        name: 'Zoom',
        description: 'A video conferencing platform for hosting virtual meetings, webinars, and training sessions.',
        useCase: 'Essential for conducting any live virtual training. Use its features like breakout rooms for small group practice, polls for instant feedback, and chat for quick engagement.',
        quickStart: '1. Create a free account on zoom.us.\n2. Schedule a new meeting to get a link.\n3. Share the link with participants.\n4. Use the controls at the bottom to manage participants, share your screen, and launch polls or breakout rooms.',
        icon: Icons.video,
        category: 'Communication',
    },
    {
        id: 'tool2',
        name: 'Padlet',
        description: 'A digital canvas that allows users to post notes, images, and links on a shared wall.',
        useCase: 'Excellent for brainstorming, collecting ideas, or as a "commitment wall". It allows everyone to contribute simultaneously and see each other\'s ideas, making collaboration visual and engaging.',
        quickStart: '1. Sign up for a free account at padlet.com.\n2. Click "Make a Padlet" and choose a format (like Wall or Shelf).\n3. Share the link in the Zoom chat.\n4. Participants can double-click anywhere to add a post.',
        icon: Icons.layoutGrid,
        category: 'Collaboration',
    },
    {
        id: 'tool3',
        name: 'Mentimeter',
        description: 'An interactive presentation tool that lets you engage your audience with live polls, word clouds, Q&As, and quizzes.',
        useCase: 'Perfect for icebreakers (word clouds), checking understanding (multiple-choice polls), and gathering anonymous feedback. It keeps the energy high and gives everyone a voice.',
        quickStart: '1. Create an account at mentimeter.com.\n2. Create a new presentation and add slides (e.g., Word Cloud, Multiple Choice).\n3. Click "Present" and share the voting code/link with your audience.\n4. Participants vote on their phones, and results appear live on your screen.',
        icon: Icons.barChart,
        category: 'Presentation',
    },
    {
        id: 'tool4',
        name: 'Google Docs',
        description: 'A collaborative word processor that allows multiple users to edit a document in real-time.',
        useCase: 'Ideal for activities where groups need to co-create content, such as summarizing key points, documenting solutions to a case study, or building a shared resource list.',
        quickStart: '1. Create a new document at docs.google.com.\n2. Click the "Share" button and set permissions to "Anyone with the link can edit".\n3. Copy the link and share it with participants.\n4. You can see everyone typing live in the document.',
        icon: Icons.fileText,
        category: 'Collaboration',
    },
    {
        id: 'tool5',
        name: 'Kahoot!',
        description: 'A game-based learning platform that makes it easy to create, share, and play fun learning games or trivia quizzes.',
        useCase: 'A fantastic way to energize the group, review key concepts in a fun and competitive way, or run a quick knowledge check. The music and leaderboard add to the excitement.',
        quickStart: '1. Sign up at kahoot.com.\n2. Create a new "kahoot" and add your questions.\n3. Start the game and share your screen in Zoom.\n4. Participants join using a PIN on their phones and compete.',
        icon: Icons.gamepad,
        category: 'Assessment',
    },
     {
        id: 'tool6',
        name: 'Miro',
        description: 'An online collaborative whiteboard platform that enables distributed teams to work effectively together.',
        useCase: 'Perfect for complex visual activities like concept mapping, timeline building, or strategic planning. Its infinite canvas allows for deep, structured collaboration.',
        quickStart: '1. Create a free account at miro.com.\n2. Choose a template (e.g., Mind Map) or start with a blank board.\n3. Invite collaborators by sharing the board link.\n4. Use sticky notes, shapes, and arrows to visualize ideas.',
        icon: Icons.gitBranch,
        category: 'Collaboration',
    },
     {
        id: 'tool7',
        name: 'Jamboard',
        description: 'A digital interactive whiteboard developed by Google, part of the Google Workspace suite.',
        useCase: 'A simple and effective tool for digital posters, quick brainstorming sessions, or collecting feedback on sticky notes. It\'s less complex than Miro, making it great for quick tasks.',
        quickStart: '1. Go to jamboard.google.com.\n2. Create a new "Jam".\n3. Share the link with edit permissions.\n4. Participants can add sticky notes, draw, or add images to the board.',
        icon: Icons.edit,
        category: 'Collaboration',
    },
    {
        id: 'tool8',
        name: 'Flipgrid',
        description: 'A video discussion platform where educators can post topics and students respond with short videos.',
        useCase: 'Excellent for personal reflection activities where participants can record their thoughts asynchronously. It encourages deeper, more considered responses than a live chat.',
        quickStart: '1. Create an educator account at flipgrid.com.\n2. Create a "Group" for your training and add a "Topic".\n3. Share the join code or link.\n4. Participants can then record and submit their video responses.',
        icon: Icons.video,
        category: 'Communication',
    }
];


// FIX: Add mock data for modules.
const INITIAL_MODULES: TrainingModule[] = [
    {
        id: 'mod1',
        title: 'Principles of Clinical Pharmacy',
        category: 'Pharmaceutical Knowledge',
        description: 'A foundational module covering the key concepts in clinical pharmacy.',
        content: 'Content covers the history of pharmacy, the role of the pharmacist, medication review, and common drug interactions.',
        quiz: [
// FIX: The QuizQuestion type expects `correctAnswer` to be a string, not `correctAnswerIndex`. Also added missing `type` property.
            { question: 'What is the primary role of a clinical pharmacist?', type: 'multiple-choice', options: ['Selling drugs', 'Ensuring the safe and effective use of medications', 'Inventory management', 'Marketing'], correctAnswer: 'Ensuring the safe and effective use of medications' }
        ]
    },
    {
        id: 'mod2',
        title: 'Effective Communication Skills',
        category: 'Soft Skills',
        description: 'Developing communication skills for interacting with patients and colleagues.',
        content: 'The module includes techniques for active listening, patient counseling, and handling difficult situations.',
        quiz: []
    }
];

// FIX: Add mock data for trainees.
const INITIAL_TRAINEES: Trainee[] = [
    { id: 'trn1', name: 'Ahmed Mahmoud', employeeId: 'EMP001', branch: 'Riyadh Branch', role: 'Pharmacist', completedModules: ['mod1'] },
    { id: 'trn2', name: 'Fatima Al-Zahra', employeeId: 'EMP002', branch: 'Jeddah Branch', role: 'Pharmacy Assistant', completedModules: [] },
    { id: 'trn3', name: 'Ali Hassan', employeeId: 'EMP003', branch: 'Riyadh Branch', role: 'Trainee Pharmacist', completedModules: ['mod1', 'mod2'] },
];


export const useMockData = () => {
  const [activities] = useState<TrainingActivity[]>(INITIAL_ACTIVITIES);
  const [tools] = useState<Tool[]>(INITIAL_TOOLS);
  // FIX: Add state for modules and trainees.
  const [modules, setModules] = useState<TrainingModule[]>(INITIAL_MODULES);
  const [trainees, setTrainees] = useState<Trainee[]>(INITIAL_TRAINEES);

  // FIX: Add handlers for modules to support Modules component.
  const addModule = useCallback((newModule: Omit<TrainingModule, 'id'>) => {
    setModules(prev => [...prev, { ...newModule, id: `mod${Date.now()}` }]);
  }, []);

  const updateModule = useCallback((updatedModule: TrainingModule) => {
    setModules(prev => prev.map(m => m.id === updatedModule.id ? updatedModule : m));
  }, []);


  // FIX: Return modules and trainees from the hook.
  return { activities, tools, modules, trainees, addModule, updateModule };
};